spring:
  datasource:
    druid:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: "jdbc:mysql://localhost:3306/pay?useUnicode=true&characterEncoding=UTF8"

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
logging:
  level:
    com.gloryjie.pay: debug
server:
  port: 10010
domain: "http://jierong.nat300.top"
